# Generated by Django 4.0.6 on 2022-08-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
